from datetime import datetime
from uuid import UUID
from pydantic import BaseModel, Field
from app.models.job import JobStatus


class JobBase(BaseModel):
    job_title: str = Field(..., max_length=255, description="Title of the job")
    job_code: str = Field(default="", max_length=100, description="Unique internal job code")
    department: str = Field(default="", max_length=150, description="Department name")
    
    experience_min: int | None = Field(None, ge=0, description="Minimum experience required in years")
    experience_max: int | None = Field(None, ge=0, description="Maximum experience required in years")
    vacancies: int = Field(1, ge=1, description="Number of vacancies")
    
    job_description: str = Field(..., description="Detailed job description")
    responsibilities: str = Field(default="", description="Job responsibilities")
    required_skills: list[str] = Field(default_factory=list, description="Required technical skills")
    education_requirements: str = Field(default="", description="Education requirements")
    certifications: list[str] = Field(default_factory=list, description="Required/Preferred certifications")
    
    # Optional fields
    industry: str | None = Field(None, max_length=150)
    team_name: str | None = Field(None, max_length=150)
    project_name: str | None = Field(None, max_length=150)
    internal_notes: str | None = Field(None)
    
    status: JobStatus = Field(JobStatus.DRAFT, description="Current job status")


class JobCreate(JobBase):
    company_id: UUID = Field(default=UUID("00000000-0000-0000-0000-000000000000"), description="Company ID associated with the job")



class JobUpdate(BaseModel):
    job_title: str | None = Field(None, max_length=255)
    job_code: str | None = Field(None, max_length=100)
    department: str | None = Field(None, max_length=150)
    experience_min: int | None = Field(None, ge=0)
    experience_max: int | None = Field(None, ge=0)
    vacancies: int | None = Field(None, ge=1)
    job_description: str | None = Field(None)
    responsibilities: str | None = Field(None)
    required_skills: list[str] | None = Field(None)
    education_requirements: str | None = Field(None)
    certifications: list[str] | None = Field(None)
    
    industry: str | None = Field(None, max_length=150)
    team_name: str | None = Field(None, max_length=150)
    project_name: str | None = Field(None, max_length=150)
    internal_notes: str | None = Field(None)
    
    status: JobStatus | None = Field(None)


class JobResponse(JobBase):
    job_id: UUID
    company_id: UUID
    created_by: UUID
    
    # AI generated fields
    ai_summary: str | None = None
    ai_required_skills: list[str] | None = None
    ai_job_category: str | None = None
    ai_seniority_level: str | None = None
    ai_keywords: list[str] | None = None
    ai_must_have_keywords: list[str] | None = None
    ai_nice_to_have_keywords: list[str] | None = None
    ai_tools: list[str] | None = None
    ai_technologies: list[str] | None = None
    ai_soft_skills: list[str] | None = None
    ai_domain_experience: list[str] | None = None
    ai_embedding_status: bool
    
    created_at: datetime
    updated_at: datetime

    class Config:
        from_attributes = True


class JobEmbeddingResponse(BaseModel):
    embedding_id: UUID
    job_id: UUID
    embedding_model: str
    embedding_dimension: int
    content_hash: str
    generated_at: datetime
    created_at: datetime
    updated_at: datetime

    class Config:
        from_attributes = True


class JobAISummaryResponse(BaseModel):
    job_id: UUID
    ai_summary: str | None = None
    ai_required_skills: list[str] | None = None
    ai_job_category: str | None = None
    ai_seniority_level: str | None = None
    ai_keywords: list[str] | None = None
    ai_must_have_keywords: list[str] | None = None
    ai_nice_to_have_keywords: list[str] | None = None
    ai_tools: list[str] | None = None
    ai_technologies: list[str] | None = None
    ai_soft_skills: list[str] | None = None
    ai_domain_experience: list[str] | None = None

    class Config:
        from_attributes = True


class Question(BaseModel):
    id: str = Field(..., description="Unique identifier for the question")
    question: str = Field(..., description="The question text")
    field_name: str = Field(..., description="The job field this question relates to")
    answer: str | None = Field(None, description="User's answer to the question")


class JobQuestionsResponse(BaseModel):
    job_id: UUID
    needs_clarification: bool = Field(True, description="Whether the job needs clarification")
    questions: list[Question] = Field(..., description="List of clarifying questions generated by LLM")
    message: str = Field(..., description="Message to display to the user")


class AnswerSubmission(BaseModel):
    job_id: UUID
    answers: dict[str, dict[str, str]] = Field(..., description="Dictionary mapping question IDs to {answer, field_name}")


class JobWithQuestionsResponse(BaseModel):
    """Response that can be either a job or questions depending on data sufficiency"""
    job: JobResponse | None = None
    questions: JobQuestionsResponse | None = None
    requires_answers: bool = Field(False, description="True if user needs to answer questions")
