"""create_initial_tables

Revision ID: 0d129e630f1b
Revises: 
Create Date: 2026-06-09 21:36:34.960834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy.vector

# revision identifiers, used by Alembic.
revision: str = '0d129e630f1b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Enable pgvector extension
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('role', sa.Enum('hr_manager', 'recruiter', 'hiring_manager', 'hr_admin', 'owner', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('jobs',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('job_title', sa.String(length=255), nullable=False),
    sa.Column('job_code', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=150), nullable=False),
    sa.Column('experience_min', sa.Integer(), nullable=True),
    sa.Column('experience_max', sa.Integer(), nullable=True),
    sa.Column('vacancies', sa.Integer(), nullable=False),
    sa.Column('job_description', sa.Text(), nullable=False),
    sa.Column('responsibilities', sa.Text(), nullable=False),
    sa.Column('required_skills', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('education_requirements', sa.Text(), nullable=False),
    sa.Column('certifications', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('Draft', 'Active', 'Closed', name='job_status'), nullable=False),
    sa.Column('industry', sa.String(length=150), nullable=True),
    sa.Column('team_name', sa.String(length=150), nullable=True),
    sa.Column('project_name', sa.String(length=150), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_required_skills', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('ai_job_category', sa.String(length=100), nullable=True),
    sa.Column('ai_seniority_level', sa.String(length=100), nullable=True),
    sa.Column('ai_keywords', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('ai_must_have_keywords', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('ai_nice_to_have_keywords', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('ai_tools', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('ai_technologies', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('ai_soft_skills', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('ai_domain_experience', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('ai_embedding_status', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('default_weight_experience', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('default_weight_sector', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('default_weight_tech_stack', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('default_weight_education', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('default_weight_other_skills', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('max_upload_files', sa.Integer(), nullable=False),
    sa.Column('allowed_file_types', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('job_embeddings',
    sa.Column('embedding_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(), nullable=False),
    sa.Column('embedding_model', sa.String(length=100), nullable=False),
    sa.Column('embedding_dimension', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=255), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('embedding_id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_table('resume_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_posting_id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('file_hash_md5', sa.String(length=32), nullable=True),
    sa.Column('validation_status', sa.Enum('pending', 'valid', 'invalid', name='resume_validation_status'), nullable=False),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('processing_status', sa.Enum('pending', 'processing', 'completed', 'failed', name='resume_processing_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_posting_id'], ['jobs.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_files_file_hash_md5'), 'resume_files', ['file_hash_md5'], unique=False)
    op.create_index(op.f('ix_resume_files_job_posting_id'), 'resume_files', ['job_posting_id'], unique=False)
    op.create_index(op.f('ix_resume_files_processing_status'), 'resume_files', ['processing_status'], unique=False)
    op.create_index(op.f('ix_resume_files_validation_status'), 'resume_files', ['validation_status'], unique=False)
    op.create_table('candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resume_file_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('total_experience_years', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('education_degree', sa.String(length=150), nullable=True),
    sa.Column('education_field', sa.String(length=150), nullable=True),
    sa.Column('skills', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('tech_stack', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('sector_experience', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('embedding_id', sa.String(length=200), nullable=True),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resume_file_id'], ['resume_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resume_file_id')
    )
    op.create_index(op.f('ix_candidates_full_name'), 'candidates', ['full_name'], unique=False)
    op.create_table('candidate_embeddings',
    sa.Column('embedding_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(), nullable=False),
    sa.Column('embedding_model', sa.String(length=100), nullable=False),
    sa.Column('embedding_dimension', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=255), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('embedding_id'),
    sa.UniqueConstraint('candidate_id')
    )
    op.create_table('match_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_posting_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('overall_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('score_experience', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('score_sector', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('score_tech_stack', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('score_education', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('score_other_skills', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('matched_keywords', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('unmatched_keywords', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('bm25_score', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('semantic_score', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('rank_position', sa.Integer(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_posting_id'], ['jobs.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_posting_id', 'candidate_id', name='uq_match_results_job_candidate')
    )
    op.create_index(op.f('ix_match_results_job_posting_id'), 'match_results', ['job_posting_id'], unique=False)
    op.create_index(op.f('ix_match_results_overall_score'), 'match_results', ['overall_score'], unique=False)
    op.create_index(op.f('ix_match_results_rank_position'), 'match_results', ['rank_position'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_match_results_rank_position'), table_name='match_results')
    op.drop_index(op.f('ix_match_results_overall_score'), table_name='match_results')
    op.drop_index(op.f('ix_match_results_job_posting_id'), table_name='match_results')
    op.drop_table('match_results')
    op.drop_table('candidate_embeddings')
    op.drop_index(op.f('ix_candidates_full_name'), table_name='candidates')
    op.drop_table('candidates')
    op.drop_index(op.f('ix_resume_files_validation_status'), table_name='resume_files')
    op.drop_index(op.f('ix_resume_files_processing_status'), table_name='resume_files')
    op.drop_index(op.f('ix_resume_files_job_posting_id'), table_name='resume_files')
    op.drop_index(op.f('ix_resume_files_file_hash_md5'), table_name='resume_files')
    op.drop_table('resume_files')
    op.drop_table('job_embeddings')
    op.drop_table('settings')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
