"""add phone_number to users

Revision ID: 517ac8fa5184
Revises: d836978490c4
Create Date: 2026-06-13 19:19:33.068358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '517ac8fa5184'
down_revision: Union[str, Sequence[str], None] = 'd836978490c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ats_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('config_name', sa.String(length=100), nullable=False),
    sa.Column('weight_must_have', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('weight_semantic', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('weight_project_impact', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('weight_domain', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('weight_education', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('weight_exp_must_have', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('weight_exp_semantic', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('weight_exp_project_impact', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('weight_exp_experience', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('weight_exp_domain', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('weight_exp_education', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('llm_weight', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('mandatory_gate_threshold', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('gate_penalty_multiplier', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('soft_penalty_threshold', sa.Numeric(precision=5, scale=3), nullable=False),
    sa.Column('soft_penalty_multiplier', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('confidence_min', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('confidence_exact', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('confidence_boundary', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('confidence_fuzzy', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('confidence_ontology', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('confidence_arch_family', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('retrieval_top_n', sa.Integer(), nullable=False),
    sa.Column('vector_weight', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('bm25_weight', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('vector_limit', sa.Integer(), nullable=False),
    sa.Column('bm25_limit', sa.Integer(), nullable=False),
    sa.Column('llm_rerank_top_n', sa.Integer(), nullable=False),
    sa.Column('tier_weight_mandatory', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('tier_weight_preferred', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('tier_weight_bonus', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('project_weight_complexity', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('project_weight_scale', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('project_weight_ownership', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('project_weight_impact', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('arch_family_min_skills', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id')
    )
    op.drop_column('candidates', 'ai_summary')
    op.drop_column('match_results', 'score_jd_keyword')
    op.drop_column('match_results', 'score_projects')
    op.drop_column('match_results', 'score_formatting')
    op.drop_column('match_results', 'score_job_title')
    op.drop_column('match_results', 'score_certification')
    op.drop_column('match_results', 'score_completeness')
    op.drop_column('match_results', 'hybrid_score')
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('company_name', sa.String(), nullable=True))
    op.alter_column('users', 'auth_provider',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'auth_provider',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('users', 'company_name')
    op.drop_column('users', 'phone_number')
    op.add_column('match_results', sa.Column('hybrid_score', sa.NUMERIC(precision=8, scale=4), autoincrement=False, nullable=True))
    op.add_column('match_results', sa.Column('score_completeness', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.add_column('match_results', sa.Column('score_certification', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.add_column('match_results', sa.Column('score_job_title', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.add_column('match_results', sa.Column('score_formatting', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.add_column('match_results', sa.Column('score_projects', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.add_column('match_results', sa.Column('score_jd_keyword', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.add_column('candidates', sa.Column('ai_summary', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_table('ats_configs')
    # ### end Alembic commands ###
