"""add projects_json and experience_json to candidates

Revision ID: d836978490c4
Revises: add_skill_tiers
Create Date: 2026-06-13 17:46:13.102715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd836978490c4'
down_revision: Union[str, Sequence[str], None] = 'add_skill_tiers'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('projects_json', sa.JSON(), nullable=True))
    op.add_column('candidates', sa.Column('experience_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'experience_json')
    op.drop_column('candidates', 'projects_json')
    # ### end Alembic commands ###
